SELECT 
CASE OPERATION WHEN 1 THEN 'Add' WHEN 4 THEN 'Remove' END AS OPERATION,
CLEAR.DESCRP AS 'CLEARANCE CODE',
LOGICAL_DEV.DESCRP AS 'LOGICAL DEVICE',
USERID,
DT

FROM AUDIT_LOG
INNER JOIN CLEAR ON CLEAR.ID = AUDIT_LOG.KEY1
INNER JOIN LOGICAL_DEV ON LOGICAL_DEV.ID = AUDIT_LOG.KEY2

WHERE TABLE_NAME = 'CLEAR_L'

ORDER BY DT DESC