-- Find erroneous entries in the ACCESSCREDENTIAL_R table

select * from ACCESSCREDENTIAL_R

inner join ACCESSCREDENTIAL on ACCESSCREDENTIAL.ID = ACCESSCREDENTIAL_R.USERID

where ACCESSCREDENTIAL.CARD_NUMBER != ACCESSCREDENTIAL_R.CARD_NUMBER

order by ACCESSCREDENTIAL.CARD_NUMBER


--Clear those entries
delete ac from ACCESSCREDENTIAL_R ac

inner join ACCESSCREDENTIAL on ACCESSCREDENTIAL.ID = ac.USERID

where ACCESSCREDENTIAL.CARD_NUMBER != ac.CARD_NUMBER
