--Report to export all readers, their Boardnumbers and their Portnumbers from an Existing Database

SELECT LOGICAL_DEV.DESCRP AS 'Readername' , 
    PANEL.DESCRP AS 'Panel description', 
    SPANEL.HWDESCRP AS BOARDNAME, 
    PW5000_PANEL_M.ADDRESS_ON_PORT AS BOARDADDR, 
    RIGHT(PW5000_PANEL_R.ID,1) AS READERPORT
FROM PW5000_PANEL_R
INNER JOIN LOGICAL_DEV_D on LOGICAL_DEV_D.HARDWARE_ID = PW5000_PANEL_R.ID
INNER JOIN LOGICAL_DEV ON LOGICAL_DEV.ID = LOGICAL_DEV_D.ID
INNER JOIN PANEL ON PANEL.ID = LOGICAL_DEV.PANEL
INNER JOIN PW5000_PANEL_M ON LEFT(PW5000_PANEL_R.ID,21) = PW5000_PANEL_M.ID
INNER JOIN SPANEL ON LEFT(PW5000_PANEL_R.ID,21) = SPANEL.ID

ORDER BY LOGICAL_DEV.DESCRP