SELECT
    LOGDEVDESCRP,
    EVNT_DAT,
    CARDNO,
    EVNT_DESCRP
FROM
    EV_LOG
WHERE
    (
        LOGDEVDESCRP = 'T.3-2.01.01'
        OR LOGDEVDESCRP = 'T.3-2.01.02'
        OR LOGDEVDESCRP = 'T.3-3.01.03'
    )
    AND EVNT_DAT > GETDATE() -7