SELECT
    DISTINCT [EVNT_DAT],
    [EVNT_DESCRP],
    [LOGDEVDESCRP],
    [CARDNO],
    [STAT_COD],
    [ISSUE_LEV]
FROM
    [PWNT].[dbo].[EV_LOG]
    INNER JOIN BADGE_C ON BADGE_C.CARDNO = EV_LOG.CARDNO
    INNER JOIN BADGE_V ON BADGE_V.ID = BADGE_C.ID
WHERE
    LOGDEVDESCRP = 'CHBS/WSJ/503/00CR03/Speedlane Lobby - Reader'
    OR LOGDEVDESCRP = 'CHBS/WSJ/503/00CR04/Speedlane Lobby - Reader'