SELECT
    [EVNT_DAT],
    [EVNT_DESCRP],
    [LOGDEVDESCRP],
    [CARDNO],
    [LNAME],
    [FNAME],
    [STAT_COD],
    [ISSUE_LEV]
FROM
    [PWNT].[dbo].[EV_LOG]
WHERE
    EVNT_DAT >= DATEADD(DAY, -31, GETDATE())
    AND (
        EVNT_DESCRP = 'Antipassback error'
        OR EVNT_DESCRP = 'Local Grant'
        OR EVNT_DESCRP = 'Valid card at an unauthorized reader'
        OR EVNT_DESCRP = 'Expired Card Attempt'
        OR EVNT_DESCRP = 'Unknown Card'
        OR EVNT_DESCRP = 'Invalid Forward Card Read'
    )
    AND (
        LOGDEVDESCRP = 'FRRU/CR20 LB-R6-A1-SECURITY ROOM(6.007A)'
        OR LOGDEVDESCRP = 'FRRU/CR21 LB-R6-A2-SECURITY ROOM (6.047)'
        OR LOGDEVDESCRP = 'FRRU/CR22 LB-R6-A1-SECURITY ROOM(6.007B)'
        OR LOGDEVDESCRP = 'FRRU/CR35 LB-R6-C2-SECURITY ROOM (6.118)'
        OR LOGDEVDESCRP = 'FRRU/CR37 LB-R6-C2-SU BUR'
        OR LOGDEVDESCRP = 'FRRU/CR65 LB-R6-B2-SECURITY ROOM (6.080)'
        OR LOGDEVDESCRP = 'FRRU/CR57 LB-R7-C1-SECURITY ROOM (7.090)'
        OR LOGDEVDESCRP = 'FRRU/CR62 LB-R7-C2-SECURITY ROOM (7.105)'
        OR LOGDEVDESCRP = 'FRRU/CR34 CA-BUR-E6-C2'
        OR LOGDEVDESCRP = 'FRRU/CR10 LB-R1-B2 FACTORY 2'
        OR LOGDEVDESCRP = 'FRRU/CR09 LB-R1-B2 FACTORY 1'
    )
