SELECT
    CLEAR.DESCRP,
    LOGICAL_DEV.DESCRP
FROM
    CLEAR
    INNER JOIN CLEAR_L ON CLEAR.ID = CLEAR_L.ID
    INNER JOIN LOGICAL_DEV ON LOGICAL_DEV.ID = CLEAR_L.LOGICALDEV_ID
ORDER BY
    CLEAR.DESCRP,
    LOGICAL_DEV.DESCRP