--unfinished
SELECT
    PANEL.DESCRP AS 'PANEL',
    SPANEL.HWDESCRP AS 'Subpanel',
    SPANEL.INSTALLED AS 'Installed',
    LOGICAL_DEV.DESCRP,
    LOGICAL_DEV.PANEL,
    SPANEL.PPID
FROM
    SPANEL
    INNER JOIN PANEL ON PANEL.ID = SPANEL.PPID
    INNER JOIN LOGICAL_DEV ON LOGICAL_DEV.PANEL = PANEL.ID
ORDER BY
    LOGICAL_DEV.DESCRP ASC