--Report selecting all Inputs which are assigned to a logical device
SELECT
    INPUT.ID AS INPUTID,
    PANEL.DESCRP AS Zentrale,
    INPUT.HWDESCRP,
    PW5000_PANEL_M.ADDRESS_ON_PORT AS BOARDADDR,
    RIGHT(LOGICAL_DEV_D.HARDWARE_ID, 1) AS PORTNR,
    PW5000_PANEL_I.DISPLAY_NAME
FROM
    INPUT
    FULL OUTER JOIN PW5000_PANEL_I ON INPUT.ID = PW5000_PANEL_I.ID
    FULL OUTER JOIN LOGICAL_DEV_D ON LOGICAL_DEV_D.HARDWARE_ID = INPUT.ID
    FULL OUTER JOIN PANEL ON PANEL.ID = LEFT(INPUT.ID, 17)
    FULL OUTER JOIN PW5000_PANEL_M ON LEFT(INPUT.ID, 21) = PW5000_PANEL_M.ID
WHERE
    NOT(PANEL.DESCRP = 'HSDK Panel')
    AND NOT (INPUT.HWDESCRP LIKE 'Unused%')
    AND NOT (INPUT.HWDESCRP LIKE 'Nicht verwendeter%')
