SELECT
    CLEAR.DESCRP AS 'Clearance Code',
    LOGICAL_DEV.DESCRP AS 'Logical Device'
FROM
    CLEAR
    INNER JOIN CLEAR_L ON CLEAR.ID = CLEAR_L.ID
    INNER JOIN LOGICAL_DEV ON CLEAR_L.LOGICALDEV_ID = LOGICAL_DEV.ID
GROUP BY
    CLEAR.DESCRP,
    LOGICAL_DEV.DESCRP
ORDER BY
    CLEAR.DESCRP
